name: release-aggregate

on:
  push:
    branches: [ "main" ]
    paths:
      # Ne relance que si des "vrais" fichiers changent (scripts, etc.)
      - "*"
      - "!README*"
      - "!LICENSE*"
      - "!.github/**"
      - "!templates/**"
      - "!tools/**"
  workflow_dispatch:

permissions:
  contents: write   # créer tags + releases

concurrency:
  group: release-aggregate
  cancel-in-progress: false

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set timezone (Europe/Brussels)
        run: sudo timedatectl set-timezone Europe/Brussels

      - name: Prepare environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Aggregate & publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RETAIN: "5"            # garder uniquement les 5 dernières releases
          BRANCH_DEFAULT: "main" # réservé si besoin plus tard
        run: |
          bash .github/scripts/aggregate_release.sh
