name: test-vars
on: workflow_dispatch
jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      TARGET_HUGO_REPO: ${{ vars.TARGET_HUGO_REPO }}
      HUGO_DEMO_TOKEN: ${{ secrets.HUGO_DEMO_TOKEN }}
    steps:
      - name: Sanity check
        run: |
          set -euo pipefail
          [ -n "${TARGET_HUGO_REPO:-}" ] || { echo "::error ::TARGET_HUGO_REPO manquante"; exit 1; }
          [ -n "${HUGO_DEMO_TOKEN:-}" ]  || { echo "::error ::HUGO_DEMO_TOKEN manquant"; exit 1; }
          echo "TARGET_HUGO_REPO=${TARGET_HUGO_REPO}"
          echo "HUGO_DEMO_TOKEN est défini (masqué)"
